In [3]:
import numpy as np

#basics (3p)
vec1=np.array([2,3,4])#r3안에 벡터공간 만든것
mat1=np.array([[1,2,3],[4,5,6]])
print(vec1)
print(mat1)

[2 3 4]
[[1 2 3]
 [4 5 6]]


In [14]:
#Norms(4p) - implement function(student)
def cal_norm(vec, p):
    value = 0
    if p == 2:
        for element in vec:
            value += element**2
            value = value**0.5
            
    elif p == 1:
        for element in vec:
            value += np.absolute(element)
    return value

print(cal_norm(vec1, 1))
print(cal_norm(vec1, 2))

6
3.3520244595616826


In [15]:
# 파이썬의 numpy 모듈을 np로 임포트합니다.
import numpy as np

# cal_norm 함수를 정의합니다. 이 함수는 주어진 벡터의 p-노름을 계산합니다.
def cal_norm(vec, p):
    # value 변수를 초기화합니다.
    value = 0
    
    # 만약 p가 2인 경우, 벡터의 각 원소의 제곱을 더한 후 제곱근을 계산합니다.
    if p == 2:
        for element in vec:
            value += element**2
        value = value**0.5
            
    # 만약 p가 1인 경우, 벡터의 각 원소의 절댓값을 더합니다.
    elif p == 1:
        for element in vec:
            value += np.absolute(element)
            
    # 최종적으로 계산된 값(value)을 반환합니다.
    return value

# 테스트용 벡터를 정의합니다.
vec1 = [1, 2, 3]

# p=1일 때의 노름을 계산하고 출력합니다.
print(cal_norm(vec1, 1))

# p=2일 때의 노름을 계산하고 출력합니다.
print(cal_norm(vec1, 2))

6
3.7416573867739413
